runtime: python312
instance_class: F4
entrypoint: gunicorn -b :$PORT main:app
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 2
  max_instances: 32
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10